language: ruby
services:
  - postgresql
  - elasticsearch
before_script:
  - psql -c 'create database forum_api_test;' -U postgres
before_install:
  - bash -c "yes | gem uninstall -i /home/travis/.rvm/gems/ruby-2.5.1@global rake"
